import type { Topic } from '@/types/topic';

export const topics: Topic[] = [
  // Phase 1: 기초 자료구조
  {
    id: 'array',
    title: '배열 (Array)',
    category: 'data-structure',
    phase: 1,
    difficulty: 'beginner',
    description: '연속된 메모리 공간에 같은 타입의 데이터를 순서대로 저장하는 가장 기본적인 자료구조',
    realLifeAnalogy: '사물함처럼 번호가 매겨진 칸에 물건을 넣는 것',
    prerequisites: [],
    icon: 'grid',
  },
  {
    id: 'linked-list',
    title: '연결 리스트 (Linked List)',
    category: 'data-structure',
    phase: 1,
    difficulty: 'beginner',
    description: '각 데이터가 다음 데이터의 위치를 기억하며 연결된 자료구조',
    realLifeAnalogy: '보물찾기 게임처럼 각 단서가 다음 단서의 위치를 알려주는 것',
    prerequisites: ['array'],
    icon: 'link',
  },
  {
    id: 'stack',
    title: '스택 (Stack)',
    category: 'data-structure',
    phase: 1,
    difficulty: 'beginner',
    description: '마지막에 넣은 데이터를 가장 먼저 꺼내는 LIFO 구조',
    realLifeAnalogy: '접시 쌓기 — 맨 위에 올린 접시를 먼저 꺼내는 것',
    prerequisites: ['array'],
    icon: 'layers',
  },
  {
    id: 'queue',
    title: '큐 (Queue)',
    category: 'data-structure',
    phase: 1,
    difficulty: 'beginner',
    description: '먼저 넣은 데이터를 가장 먼저 꺼내는 FIFO 구조',
    realLifeAnalogy: '편의점 줄 서기 — 먼저 줄 선 사람이 먼저 계산하는 것',
    prerequisites: ['array'],
    icon: 'arrow-right',
  },
  {
    id: 'hash-table',
    title: '해시 테이블 (Hash Table)',
    category: 'data-structure',
    phase: 1,
    difficulty: 'intermediate',
    description: '키-값 쌍으로 데이터를 저장하여 빠르게 검색할 수 있는 자료구조',
    realLifeAnalogy: '전화번호부 — 이름(키)으로 전화번호(값)를 바로 찾는 것',
    prerequisites: ['array'],
    icon: 'hash',
  },

  // Phase 2: 트리 & 그래프
  {
    id: 'binary-tree',
    title: '이진 트리 (Binary Tree)',
    category: 'data-structure',
    phase: 2,
    difficulty: 'intermediate',
    description: '각 노드가 최대 2개의 자식을 가지는 계층적 자료구조',
    realLifeAnalogy: '가족 족보처럼 위에서 아래로 가지가 뻗어나가는 구조',
    prerequisites: ['linked-list'],
    icon: 'git-branch',
  },
  {
    id: 'heap',
    title: '힙 (Heap)',
    category: 'data-structure',
    phase: 2,
    difficulty: 'intermediate',
    description: '부모 노드가 항상 자식보다 크거나(최대힙) 작은(최소힙) 완전 이진 트리',
    realLifeAnalogy: '회사 조직도 — 상사가 항상 부하직원보다 직급이 높은 구조',
    prerequisites: ['binary-tree'],
    icon: 'triangle',
  },
  {
    id: 'graph',
    title: '그래프 (Graph)',
    category: 'data-structure',
    phase: 2,
    difficulty: 'intermediate',
    description: '정점(노드)과 간선으로 관계를 표현하는 자료구조',
    realLifeAnalogy: '지하철 노선도 — 역(정점)과 연결된 노선(간선)의 관계',
    prerequisites: ['linked-list'],
    icon: 'share-2',
  },

  // Phase 3: 핵심 알고리즘
  {
    id: 'sorting',
    title: '정렬 알고리즘 (Sorting)',
    category: 'algorithm',
    phase: 3,
    difficulty: 'beginner',
    description: '데이터를 특정 순서대로 나열하는 알고리즘 (버블, 선택, 삽입, 병합, 퀵)',
    realLifeAnalogy: '키 순서대로 줄 서기 — 옆 사람과 비교하며 자리를 바꾸는 것',
    prerequisites: ['array'],
    icon: 'arrow-up-down',
  },
  {
    id: 'binary-search',
    title: '이진 탐색 (Binary Search)',
    category: 'algorithm',
    phase: 3,
    difficulty: 'beginner',
    description: '정렬된 배열에서 반씩 줄여가며 빠르게 찾는 탐색 알고리즘',
    realLifeAnalogy: '사전에서 단어 찾기 — 가운데를 펴서 앞/뒤 절반을 버리는 것',
    prerequisites: ['array', 'sorting'],
    icon: 'search',
  },
  {
    id: 'bfs-dfs',
    title: 'BFS / DFS',
    category: 'algorithm',
    phase: 3,
    difficulty: 'intermediate',
    description: '그래프/트리를 탐색하는 두 가지 방법: 너비 우선 vs 깊이 우선',
    realLifeAnalogy: 'BFS = 동심원처럼 가까운 곳부터 탐색, DFS = 한 길을 끝까지 가보는 것',
    prerequisites: ['graph', 'stack', 'queue'],
    icon: 'compass',
  },
  {
    id: 'recursion',
    title: '재귀 & 백트래킹',
    category: 'algorithm',
    phase: 3,
    difficulty: 'intermediate',
    description: '함수가 자기 자신을 호출하여 문제를 작은 단위로 분할하는 기법',
    realLifeAnalogy: '러시안 인형(마트료시카) — 큰 인형 안에 작은 인형이 반복되는 구조',
    prerequisites: ['stack'],
    icon: 'repeat',
  },

  // Phase 4: 심화 알고리즘
  {
    id: 'dynamic-programming',
    title: '동적 프로그래밍 (DP)',
    category: 'algorithm',
    phase: 4,
    difficulty: 'advanced',
    description: '큰 문제를 작은 하위 문제로 나누어 풀고 결과를 재활용하는 기법',
    realLifeAnalogy: '피보나치 수열 — 이전에 계산한 결과를 메모해두고 다시 쓰는 것',
    prerequisites: ['recursion'],
    icon: 'table',
  },
  {
    id: 'greedy',
    title: '그리디 (Greedy)',
    category: 'algorithm',
    phase: 4,
    difficulty: 'advanced',
    description: '매 순간 가장 좋아 보이는 선택을 하여 최적해를 구하는 전략',
    realLifeAnalogy: '거스름돈 — 가장 큰 동전부터 먼저 주는 전략',
    prerequisites: ['sorting'],
    icon: 'zap',
  },
  {
    id: 'shortest-path',
    title: '최단 경로 (Dijkstra)',
    category: 'algorithm',
    phase: 4,
    difficulty: 'advanced',
    description: '그래프에서 출발점부터 모든 정점까지의 최단 거리를 구하는 알고리즘',
    realLifeAnalogy: '네비게이션 — 출발지에서 목적지까지 가장 빠른 길을 찾는 것',
    prerequisites: ['graph', 'heap'],
    icon: 'map-pin',
  },
];
